sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run ci
  - codecov
notifications:
  email: false
